-- Créditos ao Lucas (@spallacety)
CREATE OR REPLACE FUNCTION INSERT(tabela TEXT, valores TEXT, hasPrimaryKey BOOLEAN) 
RETURNS VOID 
AS $$
	DECLARE
	    query TEXT := 'INSERT INTO ' || tabela || ' VALUES (' || valores || ');';
	BEGIN
        IF hasPrimaryKey = TRUE THEN
            query := 'INSERT INTO ' || tabela || ' VALUES (DEFAULT, ' || valores || ');';
        END IF;
        EXECUTE query;
	END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION DESCONTO_APLICADO(NOME VARCHAR(60), PORCENTAGEM DECIMAL(3,2))
RETURNS text
AS $$
BEGIN
    IF (PORCENTAGEM > 0.0) THEN
        RETURN format('Desconto de %1$s%% aplicado ao item %2$s', PORCENTAGEM * 100, NOME);
    ELSE
        RETURN format('O desconto no item %1$s foi retirado', NOME);
    END IF;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION APLICAR_DESCONTO(TIPO VARCHAR(15), NOME VARCHAR(60), PORCENTAGEM DECIMAL(3,2))
RETURNS text
AS $$
DECLARE
    COD_PROD INT;
    COD_CAT INT;
    COD_MARC INT;
BEGIN
    IF (UPPER(TIPO) = 'PRODUTO') THEN
        SELECT COD_PRODUTO INTO COD_PROD FROM PRODUTO WHERE UPPER(NOME_PRODUTO) LIKE UPPER(NOME);
        IF COD_PROD IS NOT NULL THEN
            UPDATE PRODUTO SET TAXA_PRODUTO = PORCENTAGEM WHERE COD_PRODUTO = COD_PROD;
            RETURN DESCONTO_APLICADO(NOME, PORCENTAGEM);
        ELSE
            RETURN format('O produto %1$s não existe!', NOME);
        END IF;
    END IF;
    IF (UPPER(TIPO) = 'CATEGORIA') THEN
        SELECT COD_CATEGORIA INTO COD_CAT FROM CATEGORIA WHERE UPPER(NOME_CATEGORIA) LIKE UPPER(NOME);
        IF COD_CAT IS NOT NULL THEN
            UPDATE CATEGORIA SET TAXA_CATEGORIA = PORCENTAGEM WHERE COD_CATEGORIA = COD_CAT;
            RETURN DESCONTO_APLICADO(NOME, PORCENTAGEM);
        ELSE
            RETURN format('A categoria %1$s não existe!', NOME);
        END IF;
    END IF;
    IF (UPPER(TIPO) = 'MARCA') THEN
        SELECT COD_MARCA INTO COD_MARC FROM MARCA WHERE UPPER(NOME_MARCA) LIKE UPPER(NOME);
        IF COD_MARC IS NOT NULL THEN
            UPDATE MARCA SET TAXA_MARCA = PORCENTAGEM WHERE COD_MARCA = COD_MARC;
            RETURN DESCONTO_APLICADO(NOME, PORCENTAGEM);
        ELSE
            RETURN format('A marca %1$s não existe!', NOME);
        END IF;
    END IF;
    RETURN 'O tipo inserido é inválido! Selecione entre PRODUTO, CATEGORIA e MARCA!';
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION RESETAR_DESCONTO(TIPO VARCHAR(15), NOME VARCHAR(60))
RETURNS text
AS $$
BEGIN
    RETURN APLICAR_DESCONTO(TIPO, NOME, 0.0);
END;
$$ LANGUAGE 'plpgsql';

-- Função para obter o preço do produto com o seu desconto 
CREATE OR REPLACE FUNCTION OBTER_PRECO_DESCONTADO(COD_ITEM INT)
RETURNS DECIMAL(10,2)
AS $$
DECLARE
    VALOR_PRODUTO DECIMAL(10,2);
    DESCONTO_PRODUTO DECIMAL(10,2);
    DESCONTO_CATEGORIA DECIMAL(10,2);
    DESCONTO_MARCA DECIMAL(10,2);
BEGIN
    SELECT VALOR INTO VALOR_PRODUTO FROM PRODUTO WHERE COD_PRODUTO = COD_ITEM;
    SELECT TAXA_PRODUTO INTO DESCONTO_PRODUTO FROM CATALOGO WHERE COD_PRODUTO = COD_ITEM;
    SELECT TAXA_CATEGORIA INTO DESCONTO_CATEGORIA FROM CATALOGO WHERE COD_PRODUTO = COD_ITEM;
    SELECT TAXA_MARCA INTO DESCONTO_MARCA FROM CATALOGO WHERE COD_PRODUTO = COD_ITEM;
    IF (DESCONTO_PRODUTO > 0.0) THEN 
        RETURN VALOR_PRODUTO - (VALOR_PRODUTO * DESCONTO_PRODUTO); 
    END IF;
    IF (DESCONTO_CATEGORIA > 0.0) THEN
        RETURN VALOR_PRODUTO - (VALOR_PRODUTO * DESCONTO_CATEGORIA);
    END IF;
    IF (DESCONTO_MARCA > 0.0) THEN
        RETURN VALOR_PRODUTO - (VALOR_PRODUTO * DESCONTO_MARCA);
    END IF;
    RETURN VALOR_PRODUTO;
END;
$$ LANGUAGE 'plpgsql';

-- Função que verifica a compatibilidade dos itens no carrinho e avisa o usuário sobre
CREATE OR REPLACE FUNCTION VERIFICAR_COMPATIBILIDADE(COD_CART INT)
RETURNS text
AS $$
DECLARE
   COD_PLACA INT;
   COD_PROD INT;
   COUNTER INT := 0;
   PRODUTOS TEXT;
   LINHA RECORD;
   MESSAGE TEXT := 'mas há produtos incompatíveis no carrinho!';
BEGIN
    SELECT COD_PRODUTO INTO COD_PLACA FROM OBTER_CARRINHO(COD_CART) WHERE TIPO = 'Placa-mãe';
    PRODUTOS := format('(SELECT * FROM ITEM_CARRINHO NATURAL JOIN CATEGORIA WHERE COD_CARRINHO = %1$s);', COD_CART);
    IF COD_PLACA IS NOT NULL THEN
        FOR LINHA IN EXECUTE PRODUTOS LOOP
            IF (SELECT COUNT(*) FROM COMPATIBILIDADE WHERE COD_CATEGORIA_PRIMARIA = COD_PLACA AND COD_CATEGORIA_SECUNDARIA = LINHA.COD_CATEGORIA) = 0 THEN
                COUNTER := COUNTER + 1;
            END IF;
        END LOOP;
    END IF;
    IF COUNTER <= 0 THEN
        MESSAGE := NULL;
    END IF;
    RETURN MESSAGE;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION ADICIONAR_ITEM(CPF_FUNCIONARIO VARCHAR(14), CPF_CLIENTE VARCHAR(14), NOME_ITEM VARCHAR(60), QUANTIDADE_ADICIONADA INT) 
RETURNS TEXT
AS $$
DECLARE
    COD_ITEM INT;
    COD_FUNC INT;
    COD_CART INT;
    COD_CLI INT;
    VALOR_UNITARIO DECIMAL(10,2);
    VALOR_TOTAL DECIMAL(10,2);
    MENSAGEM TEXT;
    COMPAT TEXT;
BEGIN
    -- Inicialização de variáveis
    SELECT PROCURAR_CLIENTE(CPF_CLIENTE) INTO COD_CLI;
    SELECT PROCURAR_FUNCIONARIO(CPF_FUNCIONARIO) INTO COD_FUNC;
    SELECT PROCURAR_ITEM(NOME_ITEM) INTO COD_ITEM;
    SELECT OBTER_PRECO_DESCONTADO(COD_ITEM) INTO VALOR_UNITARIO;
    SELECT OBTER_CARRINHO(COD_FUNC, COD_CLI) INTO COD_CART;

    IF (SELECT COUNT(*) FROM ITEM_CARRINHO WHERE COD_CARRINHO = COD_CART AND COD_PRODUTO = COD_ITEM) = 0 THEN
            INSERT INTO ITEM_CARRINHO VALUES(COD_ITEM, COD_CART, VALOR_UNITARIO * QUANTIDADE_ADICIONADA, QUANTIDADE_ADICIONADA);
            MENSAGEM := format('O produto %1$s foi adicionado ao carrinho (%2$s unidade(s)) com preço unitário de %3$s', NOME_ITEM, QUANTIDADE_ADICIONADA, VALOR_UNITARIO);
    ELSE -- Se já existe e o ITEM_CARRINHO também, apenas atualizar os valores
            UPDATE ITEM_CARRINHO SET QUANTIDADE = QUANTIDADE + QUANTIDADE_ADICIONADA WHERE COD_CARRINHO = COD_CART AND COD_PRODUTO = COD_ITEM;
            UPDATE ITEM_CARRINHO SET VALOR_TOTAL_ITEM = QUANTIDADE * VALOR_UNITARIO WHERE COD_CARRINHO = COD_CART AND COD_PRODUTO = COD_ITEM;
            SELECT QUANTIDADE INTO QUANTIDADE_ADICIONADA FROM ITEM_CARRINHO WHERE COD_CARRINHO = COD_CART AND COD_PRODUTO = COD_ITEM;
            MENSAGEM := format('O produto %1$s foi atualizado no carrinho (%2$s unidade(s)) com preço unitário de %3$s', NOME_ITEM, QUANTIDADE_ADICIONADA, VALOR_UNITARIO);
    END IF;

    SELECT ATUALIZAR_CARRINHO(COD_CART) INTO VALOR_TOTAL;
    SELECT VERIFICAR_COMPATIBILIDADE(COD_CART) INTO COMPAT;

    IF COMPAT IS NOT NULL THEN
        MENSAGEM := MENSAGEM || ' ' || COMPAT;
    END IF;

    RETURN MENSAGEM;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION REMOVER_ITEM(COD_CART INT, COD_ITEM INT, A_REMOVER INT)
RETURNS TEXT
AS $$
DECLARE
    QUANT_ATUAL INT;
    NOME_ITEM VARCHAR(60);
    VALOR_TOTAL DECIMAL(10,2);
    VALOR_UNITARIO DECIMAL(10,2);
BEGIN
    SELECT QUANTIDADE INTO QUANT_ATUAL FROM OBTER_CARRINHO(COD_CART) WHERE COD_PRODUTO = COD_ITEM;
    SELECT NOME INTO NOME_ITEM FROM OBTER_CARRINHO(COD_CART) WHERE COD_PRODUTO = COD_ITEM;
    SELECT VALOR INTO VALOR_UNITARIO FROM PRODUTO WHERE COD_PRODUTO = COD_ITEM;
    RAISE NOTICE 'Quantidade atual: % // A remover: % // Subtracao: %', QUANT_ATUAL, A_REMOVER, (QUANT_ATUAL - A_REMOVER);
    IF QUANT_ATUAL - A_REMOVER <= 0 THEN
        DELETE FROM ITEM_CARRINHO WHERE COD_CARRINHO = COD_CART AND COD_PRODUTO = COD_ITEM;
        SELECT ATUALIZAR_CARRINHO(COD_CART) INTO VALOR_TOTAL;
        RETURN format('O item %1$s foi removido do carrinho', NOME_ITEM, VALOR_TOTAL);
    ELSE
        UPDATE ITEM_CARRINHO SET QUANTIDADE = QUANTIDADE - A_REMOVER WHERE COD_CARRINHO = COD_CART AND COD_PRODUTO = COD_ITEM;
        UPDATE ITEM_CARRINHO SET VALOR_TOTAL_ITEM = (QUANTIDADE * VALOR_UNITARIO) WHERE COD_CARRINHO = COD_CART AND COD_PRODUTO = COD_ITEM;
        SELECT ATUALIZAR_CARRINHO(COD_CART) INTO VALOR_TOTAL;
        RETURN format('%1$s unidade(s) do item %2$s foi/foram removida(s) do carrinho, novo valor total: %3$s', A_REMOVER, NOME_ITEM, VALOR_TOTAL);
    END IF;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION ATUALIZAR_CARRINHO(COD_CART INT)
RETURNS DECIMAL(10,2)
AS $$
DECLARE
    VALOR_TOTAL DECIMAL(10,2);
BEGIN
    SELECT SUM(VALOR_TOTAL_ITEM) INTO VALOR_TOTAL FROM ITEM_CARRINHO WHERE COD_CARRINHO = COD_CART;
    UPDATE CARRINHO SET VALOR_TOTAL_ITENS = VALOR_TOTAL WHERE COD_CARRINHO = COD_CART;
    RETURN VALOR_TOTAL;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION OBTER_CARRINHO(COD_CART INT)
RETURNS TABLE(COD_PRODUTO INT, NOME VARCHAR(60), TIPO VARCHAR(60), VALOR DECIMAL(10,2), QUANTIDADE INT)
AS $$
BEGIN
    RETURN QUERY (SELECT CATALOGO.COD_PRODUTO, NOME_PRODUTO, DESCR_TIPO_PRODUTO, VALOR_TOTAL_ITEM, ITEM_CARRINHO.QUANTIDADE FROM ITEM_CARRINHO NATURAL JOIN CATALOGO INNER JOIN TIPO_PRODUTO ON CATALOGO.COD_TIPO_PRODUTO = TIPO_PRODUTO.COD_TIPO_PRODUTO WHERE COD_CARRINHO = COD_CART);
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION OBTER_CARRINHO(COD_FUNC INT, COD_CLI INT)
RETURNS INT
AS $$
DECLARE
   COD_CART INT;
BEGIN
    SELECT COD_CARRINHO INTO COD_CART FROM CARRINHO WHERE COD_CLIENTE = COD_CLI AND COD_FUNCIONARIO = COD_FUNC AND VENDA_FINALIZADA = FALSE;
    IF (COD_CART IS NULL) THEN
        INSERT INTO CARRINHO VALUES(DEFAULT, COD_CLI, COD_FUNC, NULL, 0.0, FALSE, CURRENT_DATE);
        SELECT COD_CARRINHO INTO COD_CART FROM CARRINHO WHERE COD_CLIENTE = COD_CLI AND COD_FUNCIONARIO = COD_FUNC AND VENDA_FINALIZADA = FALSE ORDER BY CURRENT_DATE DESC;
    END IF;
    RETURN COD_CART;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION PROCURAR_CLIENTE(CPF_CLIENTE VARCHAR(14))
RETURNS INT
AS $$
DECLARE
   COD_CLI INT;
BEGIN
    SELECT COD_CLIENTE INTO COD_CLI FROM CLIENTE NATURAL JOIN PESSOA WHERE CPF = CPF_CLIENTE AND VISIVEL = TRUE;
    IF (COD_CLI IS NULL) THEN
        RAISE EXCEPTION 'O cliente não está cadastrado!';
    END IF;
    RETURN COD_CLI;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION PROCURAR_FUNCIONARIO(CPF_FUNCIONARIO VARCHAR(14))
RETURNS INT
AS $$
DECLARE
   COD_FUNC INT;
BEGIN
    SELECT COD_FUNCIONARIO INTO COD_FUNC FROM FUNCIONARIO NATURAL JOIN PESSOA WHERE CPF = CPF_FUNCIONARIO AND VISIVEL = TRUE;
    IF (COD_FUNC IS NULL) THEN
        RAISE EXCEPTION 'O funcionário não está cadastrado!';
    END IF;
    RETURN COD_FUNC;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION PROCURAR_ITEM(NOME VARCHAR(60))
RETURNS INT
AS $$
DECLARE
   COD_ITEM INT;
BEGIN
    SELECT COD_PRODUTO INTO COD_ITEM FROM PRODUTO WHERE NOME_PRODUTO ILIKE '%' || NOME || '%' AND VISIVEL = TRUE;
    IF (COD_ITEM IS NULL) THEN
        RAISE EXCEPTION 'O item desejado não está cadastrado!';
    END IF;
    RETURN COD_ITEM;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION PROCURAR_TIPO_PAGAMENTO(NOME VARCHAR(60))
RETURNS INT
AS $$
DECLARE
   COD_ITEM INT;
BEGIN
    SELECT COD_TIPO_PAGAMENTO INTO COD_ITEM FROM TIPO_PAGAMENTO WHERE DESCRICAO ILIKE '%' || NOME || '%';
    IF (COD_ITEM IS NULL) THEN
        RAISE EXCEPTION 'A forma de pagamento desejada está indisponível!';
    END IF;
    RETURN COD_ITEM;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION OBTER_SALARIO_FUNCIONARIO(CPF VARCHAR(60))
RETURNS DECIMAL(10,2)
AS $$
DECLARE
    COD_FUNC INT;
    QUERY TEXT;
    LINE RECORD;
    SALARIO_FINAL DECIMAL(10,2);
    ACRESCIMO DECIMAL(10,2) := 0.0;
    TAXA_POR_VENDA DECIMAL(3,2) := 0.02;
BEGIN
    RETURN OBTER_SALARIO_FUNCIONARIO(CPF, EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE));
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION OBTER_SALARIO_FUNCIONARIO(CPF VARCHAR(60), MES INT)
RETURNS DECIMAL(10,2)
AS $$
DECLARE
    COD_FUNC INT;
    QUERY TEXT;
    LINE RECORD;
    SALARIO_FINAL DECIMAL(10,2);
    ACRESCIMO DECIMAL(10,2) := 0.0;
    TAXA_POR_VENDA DECIMAL(3,2) := 0.02;
BEGIN
    RETURN OBTER_SALARIO_FUNCIONARIO(CPF, MES, EXTRACT(YEAR FROM CURRENT_DATE));
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION OBTER_SALARIO_FUNCIONARIO(CPF VARCHAR(60), MES INT, ANO INT)
RETURNS DECIMAL(10,2)
AS $$
DECLARE
    COD_FUNC INT;
    QUERY TEXT;
    LINE RECORD;
    SALARIO_FINAL DECIMAL(10,2);
    ACRESCIMO DECIMAL(10,2) := 0.0;
    TAXA_POR_VENDA DECIMAL(3,2) := 0.02;
BEGIN
    SELECT PROCURAR_FUNCIONARIO(CPF) INTO COD_FUNC;
    SELECT SALARIO INTO SALARIO_FINAL FROM FUNCIONARIO WHERE COD_FUNCIONARIO = COD_FUNC;
    QUERY := format('SELECT * FROM FUNCIONARIO NATURAL JOIN CARRINHO WHERE VENDA_FINALIZADA = TRUE AND COD_FUNCIONARIO = %1$s AND EXTRACT(MONTH FROM DATA_CRIACAO) = %2$s AND EXTRACT(YEAR FROM DATA_CRIACAO) = %3$s', COD_FUNC, MES, ANO);
    FOR LINE IN EXECUTE QUERY LOOP
        ACRESCIMO := ACRESCIMO + (LINE.VALOR_TOTAL_ITENS * TAXA_POR_VENDA);
        RAISE NOTICE 'Adicionado % ao salário final pela venda % no dia %', (LINE.VALOR_TOTAL_ITENS * TAXA_POR_VENDA), LINE.COD_CARRINHO, LINE.DATA_CRIACAO;
    END LOOP;
    RETURN SALARIO_FINAL + ACRESCIMO;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION CRIAR_CUPOM(ID_CUPOM VARCHAR(20), TAXA DECIMAL(3,2), DATA_LIMITE DATE, USOS INT)
RETURNS TEXT
AS $$
DECLARE
    COD_CUP INT;
BEGIN
    SELECT COD_CUPOM INTO COD_CUP FROM CUPOM WHERE IDENTIFICACAO = ID_CUPOM;
    IF COD_CUP IS NULL THEN
        INSERT INTO CUPOM VALUES(DEFAULT, ID_CUPOM, TAXA, DATA_LIMITE, USOS);
        RETURN format('O cupom %1$s foi criado com os valores fornecidos!', ID_CUPOM);
    ELSE
        UPDATE CUPOM SET IDENTIFICACAO = ID_CUPOM, DESCONTO = TAXA, DATA_EXPIRACAO = DATA_LIMITE, USOS_DISPONIVEIS = USOS WHERE COD_CUPOM = COD_CUP;
        RETURN format('O cupom %1$s foi atualizado com os valores fornecidos!', ID_CUPOM);
    END IF;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION CONTABILIZAR_CUPOM(COD_CUP INT)
RETURNS void
AS $$
DECLARE
    QUANT_USOS INT;
BEGIN
    SELECT USOS_DISPONIVEIS INTO QUANT_USOS FROM CUPOM WHERE COD_CUPOM = COD_CUP;
    IF QUANT_USOS - 1 < 0 THEN
        UPDATE CUPOM SET USOS_DISPONIVEIS = 0 WHERE COD_CUPOM = COD_CUP;
    ELSE
        UPDATE CUPOM SET USOS_DISPONIVEIS = USOS_DISPONIVEIS - 1 WHERE COD_CUPOM = COD_CUP;
    END IF;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION OBTER_CUPOM(ID_CUPOM VARCHAR(20))
RETURNS INT
AS $$
DECLARE
    COD_ITEM INT;
    DATA_EXP DATE;
    USOS INT;
BEGIN
    SELECT COD_CUPOM INTO COD_ITEM FROM CUPOM WHERE IDENTIFICACAO ILIKE '%' || ID_CUPOM || '%';
    IF (COD_ITEM IS NULL) THEN
        RAISE EXCEPTION 'O cupom desejado não existe!';
    ELSE
        SELECT DATA_EXPIRACAO INTO DATA_EXP FROM CUPOM WHERE COD_CUPOM = COD_ITEM;
        SELECT USOS_DISPONIVEIS INTO USOS FROM CUPOM WHERE COD_CUPOM = COD_ITEM;
        IF DATA_EXP < CURRENT_DATE THEN
            RAISE EXCEPTION 'O cupom desejado já expirou!';
        ELSIF USOS <= 0 THEN
            RAISE EXCEPTION 'O cupom desejado não pode ser mais utilizado!';
        END IF;
    END IF;
    RETURN COD_ITEM;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION OBTER_VALOR_TOTAL_CARRINHO(COD_CART INT)
RETURNS DECIMAL(10,2)
AS $$
DECLARE
    VALOR_CARRINHO DECIMAL(10,2);
    VALOR_TOTAL DECIMAL(10,2);
BEGIN
    SELECT VALOR_TOTAL_ITENS INTO VALOR_CARRINHO FROM CARRINHO WHERE COD_CARRINHO = COD_CART;
    SELECT VALOR_TOTAL_ITENS * (1 - DESCONTO) INTO VALOR_TOTAL FROM CARRINHO NATURAL JOIN CUPOM WHERE COD_CARRINHO = COD_CART;
    IF (VALOR_TOTAL IS NULL) THEN
        RETURN VALOR_CARRINHO;
    ELSE
        RETURN VALOR_TOTAL;
    END IF;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION REALIZAR_PAGAMENTO(COD_CART INT, FORMA VARCHAR(60), VALOR_RECEBIDO DECIMAL(10,2), ID_CUPOM VARCHAR(20))
RETURNS TEXT
AS $$
DECLARE
    COD_TIPO INT;
    COD_PAG INT;
    COD_CUP INT;
    DIAS_PARA_COMPENSAR INT;
    VALOR_RESTANTE DECIMAL(10,2);
    VALOR_PAGO_ATUAL DECIMAL(10,2);
    VALOR_PAGO_NECESSARIO DECIMAL(10,2);
    VALOR_DESCONTADO DECIMAL(10,2);
    DESCONTO_CUPOM DECIMAL(3,2);
    MESSAGE TEXT;
BEGIN
    SELECT PROCURAR_TIPO_PAGAMENTO(FORMA) INTO COD_TIPO;
    SELECT QUANT_DIAS_COMPENSA INTO DIAS_PARA_COMPENSAR FROM TIPO_PAGAMENTO WHERE COD_TIPO_PAGAMENTO = COD_TIPO;
    SELECT OBTER_CUPOM(ID_CUPOM) INTO COD_CUP;
    
    IF (COD_CUP IS NOT NULL) THEN
        UPDATE CARRINHO SET COD_CUPOM = COD_CUP WHERE COD_CARRINHO = COD_CART;
    END IF;

    INSERT INTO PAGAMENTO VALUES(DEFAULT, COD_TIPO, COD_CART, OBTER_VALOR_TOTAL_CARRINHO(COD_CART), VALOR_RECEBIDO, (now() + (DIAS_PARA_COMPENSAR * interval '1' day)));
    SELECT COD_PAGAMENTO INTO COD_PAG FROM PAGAMENTO WHERE COD_CARRINHO = COD_CART ORDER BY DATA_PAGO DESC LIMIT 1;
    
    SELECT VALOR_PAGO INTO VALOR_PAGO_ATUAL FROM PAGAMENTO WHERE COD_PAGAMENTO = COD_PAG;
    SELECT VALOR_TOTAL_ITENS - SUM(VALOR_PAGO) INTO VALOR_RESTANTE FROM CARRINHO NATURAL JOIN PAGAMENTO WHERE COD_CARRINHO = COD_CART GROUP BY COD_CARRINHO;
        
    IF VALOR_RESTANTE = 0 THEN
        UPDATE CARRINHO SET VENDA_FINALIZADA = TRUE WHERE COD_CARRINHO = COD_CART;
        PERFORM CONTABILIZAR_CUPOM(COD_CUP);
        MESSAGE := 'Pagamento completo com sucesso e venda finalizada';
    ELSIF VALOR_RESTANTE < 0 THEN
        UPDATE CARRINHO SET VENDA_FINALIZADA = TRUE WHERE COD_CARRINHO = COD_CART;
        PERFORM CONTABILIZAR_CUPOM(COD_CUP);
        MESSAGE := format('Pagamento completo e o cliente deve receber R$ %1$s de troco', abs(VALOR_RESTANTE));
    ELSE
        MESSAGE := format('Faltam R$ %1$s para completar o pagamento do carrinho', VALOR_RESTANTE);
    END IF;

    IF (COD_CUP IS NOT NULL) THEN
        SELECT VALOR_PAGO - VALOR_TOTAL_CARRINHO INTO VALOR_DESCONTADO FROM PAGAMENTO WHERE COD_PAGAMENTO = COD_PAG;
        MESSAGE := MESSAGE || format(' e o cupom inserido garantiu R$ %1$s de desconto', VALOR_DESCONTADO);
    END IF;
    
    RETURN MESSAGE || '!';
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION REALIZAR_PAGAMENTO(COD_CART INT, FORMA VARCHAR(60), VALOR_RECEBIDO DECIMAL(10,2))
RETURNS TEXT
AS $$
BEGIN
    RETURN REALIZAR_PAGAMENTO(COD_CART, FORMA, VALOR_RECEBIDO, NULL);
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION STATUS_CARRINHO(COD_CART INT)
RETURNS TEXT
AS $$
DECLARE
    NOME_CLI VARCHAR(60);
    NOME_FUNC VARCHAR(60);
    QUANT_TOTAL_PRODUTOS INT;
    PRECO_FINAL DECIMAL(10,2);
    PAGO BOOLEAN;
BEGIN
   SELECT NOME_CLIENTE INTO NOME_CLI FROM CLIENTE NATURAL JOIN PESSOA NATURAL JOIN CARRINHO WHERE COD_CARRINHO = COD_CART;
   SELECT NOME_FUNCIONARIO INTO NOME_FUNC FROM FUNCIONARIO NATURAL JOIN PESSOA NATURAL JOIN CARRINHO WHERE COD_CARRINHO = COD_CART;
   SELECT SUM(QUANTIDADE) INTO QUANT_TOTAL_PRODUTOS FROM OBTER_CARRINHO(COD_CART);
   SELECT OBTER_VALOR_TOTAL_CARRINHO(COD_CART) INTO PRECO_FINAL;
   RETURN format('O carrinho do cliente %1$s, atendido pelo funcionário %2$s contém %3$s itens e tem valor total de R$ %4$s', NOME_CLIENTE, NOME_FUNCIONARIO, QUANT_TOTAL_PRODUTOS, PRECO_FINAL);
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION GERENCIAR_CLIENTE(NOME VARCHAR(60), DT_NASC DATE, EMAIL VARCHAR(60), CPF_N VARCHAR(14))
RETURNS TEXT
AS $$
DECLARE
    COD_PES INT;
    COD_CLI INT;
BEGIN
    SELECT COD_PESSOA INTO COD_PES FROM PESSOA WHERE CPF = CPF_N;
    SELECT COD_CLIENTE INTO COD_CLI FROM CLIENTE WHERE COD_PESSOA = COD_PES;
    IF COD_PES IS NULL AND COD_CLI IS NULL THEN
        INSERT INTO PESSOA VALUES(DEFAULT, NOME, DT_NASC, EMAIL, CPF_N);
        INSERT INTO CLIENTE VALUES(DEFAULT, COD_PES);
        SELECT COD_CLIENTE INTO COD_CLI FROM CLIENTE WHERE COD_PESSOA = COD_PES;
        RETURN format('O cliente (%1$s) foi criado!', COD_CLI);
    ELSIF COD_PES IS NOT NULL AND COD_CLI IS NULL THEN
        UPDATE PESSOA SET NOME_PESSOA = NOME, DT_NASC_PESSOA = DT_NASC, EMAIL_PESSOA = EMAIL, CPF = CPF_N WHERE COD_PESSOA = COD_PES;
        INSERT INTO CLIENTE VALUES(DEFAULT, COD_PES);
        SELECT COD_CLIENTE INTO COD_CLI FROM CLIENTE WHERE COD_PESSOA = COD_PES;
        RETURN format('O cliente (%1$s) foi atualizado!', COD_CLI);
    ELSE
        UPDATE PESSOA SET NOME_PESSOA = NOME, DT_NASC_PESSOA = DT_NASC, EMAIL_PESSOA = EMAIL, CPF = CPF_N WHERE COD_PESSOA = COD_PES;
        UPDATE CLIENTE SET VISIVEL = TRUE WHERE COD_CLIENTE = COD_CLI;
        RETURN format('O cliente (%1$s) foi atualizado!', COD_CLI);
    END IF;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION GERENCIAR_FUNCIONARIO(NOME VARCHAR(60), DT_NASC DATE, EMAIL VARCHAR(60), CPF_N VARCHAR(14), SALARIO_N DECIMAL(10,2))
RETURNS TEXT
AS $$
DECLARE
    COD_PES INT;
    COD_FUNC INT;
BEGIN
    SELECT COD_PESSOA INTO COD_PES FROM PESSOA WHERE CPF = CPF_N;
    SELECT COD_FUNCIONARIO INTO COD_FUNC FROM FUNCIONARIO WHERE COD_PESSOA = COD_PES;
    IF COD_PES IS NULL AND COD_FUNC IS NULL THEN
        INSERT INTO PESSOA VALUES(DEFAULT, NOME, DT_NASC, EMAIL, CPF_N);
        INSERT INTO FUNCIONARIO VALUES(DEFAULT, COD_PES, SALARIO_N);
        SELECT COD_FUNCIONARIO INTO COD_FUNC FROM FUNCIONARIO WHERE COD_PESSOA = COD_PES;
        RETURN format('O funcionário (%1$s) foi criado!', COD_FUNC);
    ELSIF COD_PES IS NOT NULL AND COD_FUNC IS NULL THEN
        UPDATE PESSOA SET NOME_PESSOA = NOME, DT_NASC_PESSOA = DT_NASC, EMAIL_PESSOA = EMAIL, CPF = CPF_N WHERE COD_PESSOA = COD_PES;
        INSERT INTO FUNCIONARIO VALUES(DEFAULT, COD_PES, SALARIO_N);
        SELECT COD_FUNCIONARIO INTO COD_FUNC FROM FUNCIONARIO WHERE COD_PESSOA = COD_PES;
        RETURN format('O funcionário (%1$s) foi atualizado!', COD_FUNC);
    ELSE
        UPDATE PESSOA SET NOME_PESSOA = NOME, DT_NASC_PESSOA = DT_NASC, EMAIL_PESSOA = EMAIL, CPF = CPF_N WHERE COD_PESSOA = COD_PES;
        UPDATE FUNCIONARIO SET SALARIO = SALARIO_N, VISIVEL = TRUE WHERE COD_FUNCIONARIO = COD_FUNC;
        RETURN format('O funcionário (%1$s) foi atualizado!', COD_FUNC);
    END IF;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION REMOVER_FUNCIONARIO(CPF_FUNCIONARIO VARCHAR(14)) RETURNS TEXT
AS $$
DECLARE
    COD_FUNC INT;
BEGIN
    SELECT PROCURAR_FUNCIONARIO(CPF_FUNCIONARIO) INTO COD_FUNC;
    UPDATE FUNCIONARIO SET VISIVEL = FALSE WHERE COD_FUNCIONARIO = COD_FUNC;
    RETURN format('O funcionario (%1$s) foi deletado com sucesso!', COD_FUNC);
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION REMOVER_CLIENTE(CPF_CLIENTE VARCHAR(14)) RETURNS TEXT
AS $$
DECLARE
    COD_CLI INT;
BEGIN
    SELECT PROCURAR_CLIENTE(CPF_CLIENTE) INTO COD_CLI;
    UPDATE CLIENTE SET VISIVEL = FALSE WHERE COD_CLIENTE = COD_CLI;
    RETURN format('O cliente (%1$s) foi deletado com sucesso!', COD_CLI);
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION GERENCIAR_PRODUTO(NOME VARCHAR(60), NOVO_NOME VARCHAR(60), CATEG INT, DESCRICAO TEXT, QUANT_ESTQ INT)
RETURNS TEXT
AS $$
DECLARE
   COD_PROD INT;
BEGIN
    SELECT PROCURAR_PRODUTO(NOME) INTO COD_PROD;
    IF COD_PROD IS NULL THEN
        INSERT INTO PRODUTO VALUES(DEFAULT, NOME, DESCRICAO, CATEG, QUANT_ESTQ, 0.0, TRUE);
        RETURN format('O produto %1$s foi inserido com sucesso!', NOME);
    ELSE
        UPDATE PRODUTO SET NOME_PRODUTO = NOME, DESCR = DESCRICAO, COD_CAT = CATEG, QUANT_ESTOQUE = QUANT_ESTQ WHERE COD_PRODUTO = COD_PROD;
        RETURN format('O produto %1$s foi atualizado com sucesso!', NOME);
    END IF;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION GERENCIAR_MARCA(NOME VARCHAR(60), NOVO_NOME VARCHAR(60)) RETURNS TEXT
AS $$
DECLARE
   COD_MARC INT;
BEGIN
    SELECT PROCURAR_MARCA(NOME) INTO COD_MARC;
    IF COD_MARC IS NULL AND NOVO_NOME IS NULL THEN
        INSERT INTO MARCA VALUES(DEFAULT, NOME, 0.0, TRUE);
        RETURN format('A marca %1$s foi inserido com sucesso!', NOME);
    ELSE
        UPDATE MARCA SET NOME_MARCA = NOVO_NOME WHERE COD_MARCA = COD_MARC;
        RETURN format('A marca %1$s foi atualizada com sucesso!', NOME);
    END IF;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION GERENCIAR_CATEGORIA(NOME VARCHAR(60), NOVO_NOME VARCHAR(60), MARC INT) RETURNS TEXT
AS $$
DECLARE
   COD_CAT INT;
BEGIN
    SELECT PROCURAR_CATEGORIA(NOME) INTO COD_CAT;
    IF COD_CAT IS NULL AND NOVO_NOME IS NULL THEN
        INSERT INTO CATEGORIA VALUES(DEFAULT, NOME, MARC, 0.0, TRUE);
        RETURN format('A categoria %1$s foi inserido com sucesso!', NOME);
    ELSE
        UPDATE CATEGORIA SET NOME_CATEGORIA = NOVO_NOME, COD_MARCA = MARC WHERE COD_CATEGORIA = COD_CAT;
        RETURN format('A categoria %1$s foi atualizada com sucesso!', NOME);
    END IF;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION PROCURAR_CATEGORIA(NOME VARCHAR(60))
RETURNS INT
AS $$
DECLARE
   COD_ITEM INT;
BEGIN
    SELECT COD_CATEGORIA INTO COD_ITEM FROM CATEGORIA WHERE NOME_CATEGORIA ILIKE '%' || NOME || '%' AND VISIVEL = TRUE;
    IF (COD_ITEM IS NULL) THEN
        RAISE EXCEPTION 'O item desejado não está cadastrado!';
    END IF;
    RETURN COD_ITEM;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION REMOVER_CATEGORIA(NOME VARCHAR(60)) RETURNS TEXT
AS $$
DECLARE
    COD_ITEM INT;
BEGIN
    SELECT PROCURAR_CATEGORIA(NOME) INTO COD_ITEM;
    UPDATE COD_CATEGORIA SET VISIVEL = FALSE WHERE COD_CATEGORIA = COD_ITEM;
    RETURN 'A categoria (%1$s) foi deletada com sucesso!';
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION PROCURAR_MARCA(NOME VARCHAR(60))
RETURNS INT
AS $$
DECLARE
   COD_ITEM INT;
BEGIN
    SELECT COD_MARCA INTO COD_ITEM FROM MARCA WHERE NOME_MARCA ILIKE '%' || NOME || '%' AND VISIVEL = TRUE;
    IF (COD_ITEM IS NULL) THEN
        RAISE EXCEPTION 'O item desejado não está cadastrado!';
    END IF;
    RETURN COD_ITEM;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION REMOVER_MARCA(NOME VARCHAR(60)) RETURNS TEXT
AS $$
DECLARE
    COD_ITEM INT;
BEGIN
    SELECT PROCURAR_MARCA(NOME) INTO COD_ITEM;
    UPDATE COD_MARCA SET VISIVEL = FALSE WHERE COD_MARCA = COD_ITEM;
    RETURN 'A marca (%1$s) foi deletada com sucesso!';
END;
$$ LANGUAGE 'plpgsql';