CREATE TABLE CLIENTE (
    COD_CLIENTE SERIAL PRIMARY KEY NOT NULL,
    NOME_CLIENTE VARCHAR(60) NOT NULL,
    DT_NASC_CLIENTE DATE,
    EMAIL_CLIENTE VARCHAR(60) NOT NULL,
    CPF_CLIENTE VARCHAR(14) NOT NULL DEFAULT '000.000.000-00'
);

INSERT INTO CLIENTE VALUES(DEFAULT, 'Gildásio Filho', '1998-01-30', 'gildasiogx@gmail.com', '063.699.683-23');
INSERT INTO CLIENTE VALUES(DEFAULT, 'Gildásio Chagas', '1970-10-09', 'gildasiochagas@gmail.com', DEFAULT);
INSERT INTO CLIENTE VALUES(DEFAULT, 'Pierry Angelo', '1989-01-01', 'pierryangelo@gmail.com', DEFAULT);

CREATE TABLE FUNCIONARIO (
    COD_FUNCIONARIO SERIAL PRIMARY KEY NOT NULL,
    NOME_FUNCIONARIO VARCHAR(60) NOT NULL,
    DT_NASC_FUNCIONARIO DATE,
    CPF_FUNCIONARIO VARCHAR(14) NOT NULL DEFAULT '000.000.000-00'
);

INSERT INTO FUNCIONARIO VALUES(DEFAULT, 'Gildásfuncionário', '1998-01-30', '063.699.683-23');
INSERT INTO FUNCIONARIO VALUES(DEFAULT, 'Fulano da Silva', '1988-05-07', DEFAULT);
INSERT INTO FUNCIONARIO VALUES(DEFAULT, 'Maria Fulana', '1990-04-12', DEFAULT);

CREATE TABLE CUPOM (
    COD_CUPOM SERIAL PRIMARY KEY NOT NULL,
    IDENTIFICACAO VARCHAR(20),
    DESCONTO DECIMAL(3,2),
    DATA_EXPIRACAO DATE,
    USOS_DISPONIVEIS INT
);

CREATE TABLE TIPO_PAGAMENTO (
    COD_TIPO_PAGAMENTO SERIAL PRIMARY KEY NOT NULL,
    DESCRICAO VARCHAR(60),
    QUANT_DIAS_COMPENSA INT
);

INSERT INTO TIPO_PAGAMENTO VALUES(DEFAULT, 'CARTÃO DE CRÉDITO', 1);
INSERT INTO TIPO_PAGAMENTO VALUES(DEFAULT, 'BOLETO BANCÁRIO', 3);
INSERT INTO TIPO_PAGAMENTO VALUES(DEFAULT, 'CARTÃO DE DÉBITO', 10);
INSERT INTO TIPO_PAGAMENTO VALUES(DEFAULT, 'TRANSFERÊNCIA BANCÁRIA', 3);

CREATE TABLE FORMA_PAGAMENTO (
    COD_PAGAMENTO SERIAL PRIMARY KEY NOT NULL,
    COD_TIPO_PAGAMENTO INT NOT NULL REFERENCES TIPO_PAGAMENTO(COD_TIPO_PAGAMENTO),
    VALOR_PAGO DECIMAL(10,2)
);

CREATE TABLE CARRINHO (
    COD_CARRINHO SERIAL PRIMARY KEY NOT NULL,
    COD_CLIENTE INT NOT NULL REFERENCES CLIENTE(COD_CLIENTE),
    COD_FUNCIONARIO INT NOT NULL REFERENCES FUNCIONARIO(COD_FUNCIONARIO),
    COD_PAGAMENTO INT NOT NULL REFERENCES FORMA_PAGAMENTO(COD_PAGAMENTO),
    COD_CUPOM INT REFERENCES CUPOM(COD_CUPOM),
    VALOR_TOTAL_ITENS DECIMAL(10,2),
    VENDA_FINALIZADA BOOLEAN,
    DATA_CRIACAO DATE
);

CREATE TABLE MARCA (
    COD_MARCA SERIAL PRIMARY KEY NOT NULL,
    NOME_MARCA VARCHAR(60),
    TAXA_MARCA DECIMAL(3,2)
);

INSERT INTO MARCA VALUES(DEFAULT, 'Intel', 0.0);
INSERT INTO MARCA VALUES(DEFAULT, 'AMD', 0.0);
INSERT INTO MARCA VALUES(DEFAULT, 'NVIDIA', 0.0);

CREATE TABLE CATEGORIA (
    COD_CATEGORIA SERIAL PRIMARY KEY NOT NULL,
    COD_MARCA INT NOT NULL REFERENCES MARCA(COD_MARCA),
    NOME_CATEGORIA VARCHAR(60),
    TAXA_CATEGORIA DECIMAL(3,2)
);

INSERT INTO CATEGORIA VALUES(DEFAULT, 1, 'Core i3', 0.0);
INSERT INTO CATEGORIA VALUES(DEFAULT, 1, 'Core i5', 0.0);
INSERT INTO CATEGORIA VALUES(DEFAULT, 1, 'Core i7', 0.0);
INSERT INTO CATEGORIA VALUES(DEFAULT, 1, 'Pentium', 0.0);
INSERT INTO CATEGORIA VALUES(DEFAULT, 2, 'Ryzen 3', 0.0);
INSERT INTO CATEGORIA VALUES(DEFAULT, 2, 'Ryzen 5', 0.0);
INSERT INTO CATEGORIA VALUES(DEFAULT, 2, 'Ryzen 7', 0.0);
INSERT INTO CATEGORIA VALUES(DEFAULT, 2, 'Radeon RX', 0.0);
INSERT INTO CATEGORIA VALUES(DEFAULT, 2, 'FX', 0.0);
INSERT INTO CATEGORIA VALUES(DEFAULT, 3, 'GTX 1060', 0.0);
INSERT INTO CATEGORIA VALUES(DEFAULT, 3, 'GTX 1070', 0.0);
INSERT INTO CATEGORIA VALUES(DEFAULT, 3, 'GTX 1080', 0.0);
INSERT INTO CATEGORIA VALUES(DEFAULT, 3, 'GTX 980', 0.0);
INSERT INTO CATEGORIA VALUES(DEFAULT, 3, 'GTX 750 Ti', 0.0);

CREATE TABLE PRODUTO (
    COD_PRODUTO SERIAL PRIMARY KEY NOT NULL,
    COD_CATEGORIA INT NOT NULL REFERENCES CATEGORIA(COD_CATEGORIA),
    NOME_PRODUTO VARCHAR(60),
    DESCR TEXT,
    VALOR DECIMAL(10,2),
    QUANT_ESTOQUE INT,
    TAXA_PRODUTO DECIMAL(3,2)
);


INSERT INTO PRODUTO VALUES(DEFAULT, 5, 'Ryzen 3 1100', 'Processador Quad-core/4 threads', 400, 10, 0.0);
INSERT INTO PRODUTO VALUES(DEFAULT, 5, 'Ryzen 3 1200X', 'Processador Quad-core/4 threads', 470, 10, 0.0);
INSERT INTO PRODUTO VALUES(DEFAULT, 6, 'Ryzen 5 1400', 'Processador Quad-core/8 threads', 699.99, 10, 0.0);
INSERT INTO PRODUTO VALUES(DEFAULT, 6, 'Ryzen 5 1500X', 'Processador Quad-core/8 threads', 799.90, 10, 0.0);
INSERT INTO PRODUTO VALUES(DEFAULT, 6, 'Ryzen 5 1600', 'Processador Hexa-core/12 threads', 979.90, 10, 0.0);
INSERT INTO PRODUTO VALUES(DEFAULT, 6, 'Ryzen 5 1600X', 'Processador Hexa-core/12 threads', 1059.90, 10, 0.0);
INSERT INTO PRODUTO VALUES(DEFAULT, 7, 'Ryzen 7 1700', 'Processador Octa-core/16 threads', 1349.90, 10, 0.0);
INSERT INTO PRODUTO VALUES(DEFAULT, 7, 'Ryzen 7 1700X', 'Processador Octa-core/16 threads', 1629.90, 10, 0.0);
INSERT INTO PRODUTO VALUES(DEFAULT, 7, 'Ryzen 7 1800X', 'Processador Octa-core/16 threads', 2099.90, 10, 0.0);
INSERT INTO PRODUTO VALUES(DEFAULT, 8, 'Radeon RX 460 - 2GB', 'Placa de vídeo com 2GB VRAM', 399.90, 10, 0.0);
INSERT INTO PRODUTO VALUES(DEFAULT, 8, 'Radeon RX 460 - 4GB', 'Placa de vídeo com 4GB VRAM', 599.90, 10, 0.0);
INSERT INTO PRODUTO VALUES(DEFAULT, 8, 'Radeon RX 470 - 4GB', 'Placa de vídeo com 4GB VRAM', 899.90, 10, 0.0);
INSERT INTO PRODUTO VALUES(DEFAULT, 8, 'Radeon RX 480 - 4GB', 'Placa de vídeo com 4GB VRAM', 999.90, 10, 0.0);
INSERT INTO PRODUTO VALUES(DEFAULT, 8, 'Radeon RX 480 - 8GB', 'Placa de vídeo com 8GB VRAM', 1399.90, 10, 0.0);
INSERT INTO PRODUTO VALUES(DEFAULT, 9, 'FX 4300', 'Processador Quad-core/4 threads', 359.90, 10, 0.0);
INSERT INTO PRODUTO VALUES(DEFAULT, 9, 'FX 6300', 'Processador Hexa-core/12 threads', 399.90, 10, 0.0);
INSERT INTO PRODUTO VALUES(DEFAULT, 9, 'FX 8300', 'Processador Octa-core/16 threads', 449.90, 10, 0.0);


SELECT * FROM PRODUTO

CREATE TABLE COMPATIBILIDADE (
    COD_PRODUTO_PRIMARIO INT NOT NULL REFERENCES PRODUTO(COD_PRODUTO),
    COD_PRODUTO_SECUNDARIO INT NOT NULL REFERENCES PRODUTO(COD_PRODUTO)
);

CREATE TABLE ITEM_VENDA (
    COD_PRODUTO INT NOT NULL REFERENCES PRODUTO(COD_PRODUTO),
    COD_CARRINHO INT NOT NULL REFERENCES CARRINHO(COD_CARRINHO),
    VALOR_PRODUTO DECIMAL(10,2),
    QUANTIDADE INT
);

