CREATE TABLE CLIENTE (
    COD_CLIENTE SERIAL PRIMARY KEY NOT NULL,
    NOME_CLIENTE VARCHAR(60) NOT NULL,
    DT_NASC_CLIENTE DATE,
    EMAIL_CLIENTE VARCHAR(60) NOT NULL
);

CREATE TABLE FUNCIONARIO (
    COD_FUNCIONARIO SERIAL PRIMARY KEY NOT NULL,
    NOME_FUNCIONARIO VARCHAR(60) NOT NULL,
    DT_NASC_FUNCIONARIO DATE
);

CREATE TABLE CUPOM (
    COD_CUPOM SERIAL PRIMARY KEY NOT NULL,
    IDENTIFICACAO VARCHAR(20),
    DESCONTO DECIMAL(3,2),
    DATA_EXPIRACAO DATE,
    USOS_DISPONIVEIS INT
);

CREATE TABLE TIPO_PAGAMENTO (
    COD_TIPO_PAGAMENTO SERIAL PRIMARY KEY NOT NULL,
    DESCRICAO VARCHAR(60),
    QUANT_DIAS_COMPENSA INT
);

CREATE TABLE FORMA_PAGAMENTO (
    COD_PAGAMENTO SERIAL PRIMARY KEY NOT NULL,
    COD_TIPO_PAGAMENTO INT NOT NULL REFERENCES TIPO_PAGAMENTO(COD_TIPO_PAGAMENTO),
    VALOR_PAGO DECIMAL(10,2)
);

CREATE TABLE CARRINHO (
    COD_CARRINHO SERIAL PRIMARY KEY NOT NULL,
    COD_CLIENTE INT NOT NULL REFERENCES CLIENTE(COD_CLIENTE),
    COD_FUNCIONARIO INT NOT NULL REFERENCES FUNCIONARIO(COD_FUNCIONARIO),
    COD_PAGAMENTO INT NOT NULL REFERENCES FORMA_PAGAMENTO(COD_PAGAMENTO),
    COD_CUPOM INT REFERENCES CUPOM(COD_CUPOM),
    VALOR_TOTAL_ITENS DECIMAL(10,2),
    VENDA_FINALIZADA BOOLEAN,
    DATA_CRIACAO DATE
);

CREATE TABLE MARCA (
    COD_MARCA SERIAL PRIMARY KEY NOT NULL,
    NOME_MARCA VARCHAR(60),
    TAXA_MARCA DECIMAL(3,2)
);

CREATE TABLE CATEGORIA (
    COD_CATEGORIA SERIAL PRIMARY KEY NOT NULL,
    COD_MARCA INT NOT NULL REFERENCES MARCA(COD_MARCA),
    NOME_CATEGORIA VARCHAR(60),
    TAXA_CATEGORIA DECIMAL(3,2)
);

CREATE TABLE PRODUTO (
    COD_PRODUTO SERIAL PRIMARY KEY NOT NULL,
    COD_CATEGORIA INT NOT NULL REFERENCES CATEGORIA(COD_CATEGORIA),
    NOME_PRODUTO VARCHAR(60),
    DESCR TEXT,
    VALOR DECIMAL(10,2),
    QUANT_ESTOQUE INT,
    TAXA_PRODUTO DECIMAL(3,2)
);

CREATE TABLE COMPATIBILIDADE (
    COD_PRODUTO_PRIMARIO INT NOT NULL REFERENCES PRODUTO(COD_PRODUTO),
    COD_PRODUTO_SECUNDARIO INT NOT NULL REFERENCES PRODUTO(COD_PRODUTO)
);

CREATE TABLE ITEM_VENDA (
    COD_PRODUTO INT NOT NULL REFERENCES PRODUTO(COD_PRODUTO),
    COD_CARRINHO INT NOT NULL REFERENCES CARRINHO(COD_CARRINHO),
    VALOR_PRODUTO DECIMAL(10,2),
    QUANTIDADE INT
);